HW : Pack.o 171044039_main.o 
	g++ -o HW 171044039_main.o Pack.o

Pack.o : Pack.cpp Pack.h
	g++ -c -std=c++0x -Wall Pack.cpp

1710440309_main.o : 171044039_main.cpp
	g++ -c -std=c++0x -Wall 1710440309_main.cpp

clean:
	rm *.o HW


